# Generated by Django 4.0.4 on 2022-05-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0004_remove_galleria_image_pic_galleria_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleria',
            name='image',
        ),
        migrations.AddField(
            model_name='galleria',
            name='image_pic',
            field=models.ImageField(null=True, upload_to='pics/'),
        ),
    ]
