# Generated by Django 4.0.4 on 2022-05-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0005_remove_galleria_image_galleria_image_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleria',
            name='image_pic',
        ),
        migrations.AddField(
            model_name='galleria',
            name='image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
