# Generated by Django 4.0.4 on 2022-05-30 12:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0006_remove_galleria_image_pic_galleria_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleria',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
